site_name: 'pythonlast'
site_description: 'Main documentation for the pythonlast'
repo_url: https://github.com/4uganesh/pythonlast
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'